Rssfe 06 work in progress
rolling-scopes-school/RSS-Teams-FE pull request #12
Opened 2021-02-06 18:51 UTC by self067

1. Poppins font
2. colors constant
3. styled components
  TextRegular, TextMedium,  TextSemiBold,  TextBold    - css styles with  widths 400,500,600,700, font Poppins 16/24px  
  PageTitle,  Button,  Label,  Input  - basic styled components

2021-02-07 06:24 UTC, self067 commented
4. add Header component

2021-02-07 12:19 UTC, MadaShindeInai requested changes

2021-02-07 12:19 UTC, MadaShindeInai commented on src/components/App/index.tsx
> +import { GlobalStyle } from 'typography';
please write globalStyles in src/typography/common.css

2021-02-07 12:19 UTC, MadaShindeInai commented on src/components/App/index.tsx
> +      <GlobalStyle />
remove and add this styles to src/typography/common.css.

2021-02-07 12:19 UTC, MadaShindeInai commented on src/typography/common.css
> +  font-family: "Poppins", sans-serif;
add styles from GlobalStyles there.

2021-02-07 12:19 UTC, MadaShindeInai commented on src/typography/index.ts
> +} from '../appConstants/colors';
you should import  as `} from 'appConstants/colors';`

2021-02-07 12:19 UTC, MadaShindeInai commented on src/typography/index.ts
> +import styled, { css, createGlobalStyle } from 'styled-components';
we will not use globalStyled in this project. it can cause problems later.

2021-02-07 12:19 UTC, MadaShindeInai commented on src/typography/index.ts
> +export const GlobalStyle = createGlobalStyle`
remove and add this styles to common.css

2021-02-07 12:19 UTC, MadaShindeInai commented on src/typography/index.ts
>  export const LinkText = styled(Link)`
we can remove this now as unused. it was example

2021-02-07 12:19 UTC, MadaShindeInai commented on src/typography/index.ts
> +const StyledText = css<StyledTextProps>`
wow! newer used stc this way. Cool! Maybe we can write components and css declarations in different files ( daclarations with `css` in separate file, and import it in file with `styled.`  as components)?

2021-02-10 19:44 UTC, self067 commented on src/components/Header/index.tsx
> +import { Container } from 'components/Container';
пока перенес в styled, если ещё кому то понадобится тогда сделаем общий файл

2021-02-10 19:47 UTC, self067 commented on src/modules/EditProfile/index.tsx
> +const EditProfileWrapper = styled.div`
перенес, видимо не запушил

2021-02-10 20:19 UTC, MadaShindeInai approved these changes

2021-02-10 20:20 UTC, merged