RSSFE-44: add admin page
rolling-scopes-school/RSS-Teams-FE pull request #170
Opened 2021-08-31 17:03 UTC by besovadevka

2021-08-31 17:17 UTC, manuminsk commented on src/appConstants/index.ts
> +  { id: '3', name: 'Terminative' },
`Terminative => Terminated?`

2021-08-31 17:28 UTC, besovadevka commented on src/appConstants/index.ts
> +  { id: '3', name: 'Terminative' },
Fixed

2021-08-31 17:38 UTC, manuminsk approved these changes

2021-09-05 12:41 UTC, MadaShindeInai requested changes

2021-09-05 12:41 UTC, MadaShindeInai commented on src/modules/AdminPage/components/ContentWrapper/components/CoursesList/index.tsx
> +      {courseEditMeta ? (
!!courseEditMeta && ... , for less ?: condition

2021-09-05 12:41 UTC, MadaShindeInai commented on src/components/ModalEditCourse/index.tsx
> +      <TeamButton
i think it should be someway highlighted with css as a button. looks a little weird as for me now.

2021-09-05 12:41 UTC, MadaShindeInai commented on src/modules/AdminPage/components/ContentWrapper/index.tsx
> +  const isCourseNameUniq = (courseName: string) => {
names of the **functions** should start with verb like _go, make, shake, set_ and so on.
we start generally **boolean** variables with **is**

2021-09-05 12:41 UTC, MadaShindeInai commented on src/utils/isFieldValid.ts
> +export const isFieldValid = (
nice one!

2021-09-06 09:32 UTC, MadaShindeInai requested changes

2021-09-06 09:32 UTC, MadaShindeInai commented on src/modules/AdminPage/components/ContentWrapper/index.tsx
> +            setSearchValue(e.target.value.trim())
Also we have an issue with triming spaces in search input. Try to enter in search input 'RSS React'.
I think it can not be applied onChange.

2021-09-10 14:47 UTC, MadaShindeInai commented on src/modules/AdminPage/components/ContentWrapper/index.tsx
> +            setSearchValue(e.target.value.trim())
set it as trimLeft

2021-09-10 14:54 UTC, MadaShindeInai commented on src/modules/AdminPage/components/ContentWrapper/index.tsx
> +  const isCourseNameUniq = (courseName: string) => {
fixed

2021-09-10 14:57 UTC, MadaShindeInai commented on src/modules/AdminPage/components/ContentWrapper/components/CoursesList/index.tsx
> +      {courseEditMeta ? (
fixed

2021-09-10 14:58 UTC, MadaShindeInai commented on src/components/CommonSelectList/index.tsx
> +  const doListItemsExist = !!listItems.length;
fixed

2021-09-10 15:17 UTC, MadaShindeInai commented on src/modules/AdminPage/components/ContentWrapper/components/AddCourseBlock/components/InputsBlock/components/InputBlock/index.tsx
> +        value=""
it's unused. removed

2021-09-10 15:26 UTC, MadaShindeInai commented on src/components/ModalEditCourse/index.tsx
> +      <TeamButton
fixed

2021-09-10 15:28 UTC, MadaShindeInai commented on src/components/App/index.tsx
> +          exact
will check

2021-09-10 15:30 UTC, MadaShindeInai approved these changes

2021-09-10 15:30 UTC, merged