RSSFE-12 Modals
rolling-scopes-school/RSS-Teams-FE pull request #35
Opened 2021-02-16 09:21 UTC by self067

Сделан шаблон /modal. остальные модалки сделаны на его основе. Заголовок окна, текст и названия кнопок задаются параметрами. при отсутствии параметра cancelText кнопка будет одна. Результат работы модалки возвращается в колбэке onSubmit.
Можно сделать универсальное окно, которое полностью будет настраиваться параметрами. Но сейчас все имеющиеся в макете 5 окон реализованы. только CreatedTeam надо немного допилить в плане кнопки копирования.

2021-02-16 11:49 UTC, dariavv requested changes

2021-02-16 11:49 UTC, dariavv commented on src/components/Modal/index-origin.tsx
> +export const Modal = (props: Props) => {
you can use props destructuring)

2021-02-16 11:49 UTC, dariavv commented on src/components/Modal/index.tsx
> +  // hideOnOutsideClick?: boolean;
Please, remove the commented code.

2021-02-16 11:49 UTC, dariavv commented on src/components/Modal/index.tsx
> +  // cancelText: 'No',
Please, remove the commented code.

2021-02-16 11:49 UTC, dariavv commented on src/components/Modal/index.tsx
> +                      // console.log(children || 'children are empty');
Please, remove the commented code. Keep your code clean.

2021-02-16 11:49 UTC, dariavv commented on src/components/Modal/index.tsx
> +                      // console.log(children || 'children are empty');
Please, remove the commented code. Keep your code clean.

2021-02-16 11:49 UTC, dariavv commented on src/components/ModalCreateTeam/index.tsx
> +  // cancelText?: string;
Please, remove the commented code. Keep your code clean.

2021-02-16 11:49 UTC, dariavv commented on src/components/ModalCreateTeam/index.tsx
> +      // cancelText={cancelText}
Please, remove the commented code. Keep your code clean.

2021-02-16 11:49 UTC, dariavv commented on src/components/ModalCreated/index.tsx
> +  // const [inputValue, setInputValue] = useState<string>('');
Please, remove the commented code. Keep your code clean.

2021-02-16 11:49 UTC, dariavv commented on src/components/ModalExpel/index.tsx
> +  // okText: 'Yes!',
Please, remove the commented code. Keep your code clean.

2021-02-16 11:49 UTC, dariavv commented on src/components/ModalCreated/index.tsx
> +      // onSubmit={onSubmitModal}
Please, remove the commented code. Keep your code clean.

2021-02-18 17:19 UTC, MadaShindeInai requested changes

2021-02-18 17:19 UTC, MadaShindeInai commented on src/components/Modal/index.tsx
> +                <>
не нужна пустая обёртка <> </>

2021-02-18 17:19 UTC, MadaShindeInai commented on src/components/ModalCreated/index.tsx
> +    url("data:image/svg+xml,%0A%3Csvg width='16' height='16' viewBox='0 0 16 16' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M14.2857 15.9999H5.14284C4.68834 15.9994 4.2526 15.8186 3.
svg images should be imported.
Move it in asset svg folder and import there.

2021-02-18 17:19 UTC, MadaShindeInai commented on src/components/ModalCreated/index.tsx
> +      title={title}
{..{title, text, text2, open, onClose, cancelText}}

2021-02-18 17:19 UTC, MadaShindeInai commented on src/components/ModalCreateTeam/index.tsx
> +      title={title}
{..{title, text, open, onClose, okText}}

2021-02-18 17:19 UTC, MadaShindeInai commented on src/components/ModalExpel/index.tsx
> +      title={title}
{..{title, text, open, onClose, okText, cancelText}}

2021-02-18 17:19 UTC, MadaShindeInai commented on src/components/ModalJoin/index.tsx
> +      title={title}
{..{title, text, open, onClose, okText, cancelText}}

2021-02-18 17:19 UTC, MadaShindeInai commented on src/modules/TeamsList/components/Teams/components/MyTeam/index.tsx
> +              dispatch({ type: ACTIVE_MODAL_LEAVE, payload: true })
declare this func above and use there as variable

2021-02-18 17:19 UTC, MadaShindeInai commented on src/modules/TeamsList/components/Teams/components/TeamsHeader/index.tsx
> +              dispatch({ type: ACTIVE_MODAL_CREATE_TEAM, payload: true })
declare this func above and use there as variable

2021-02-18 17:19 UTC, MadaShindeInai commented on src/modules/TeamsList/components/Teams/components/TeamsHeader/index.tsx
> +            onClick={() => dispatch({ type: ACTIVE_MODAL_JOIN, payload: true })}
declare this func above and use there as variable

2021-02-18 17:19 UTC, MadaShindeInai commented on src/modules/TeamsList/components/Teams/components/TeamsHeader/index.tsx
> +            type={'button'}
type='button' - no need to use curly braces

2021-02-18 17:19 UTC, MadaShindeInai commented on src/modules/TeamsList/components/Teams/components/TeamsHeader/index.tsx
> +            type={'button'}
type='button' - no need to use curly braces

2021-02-18 17:19 UTC, MadaShindeInai commented on src/modules/TeamsList/components/Teams/components/MyTeam/index.tsx
> +            type={'button'}
type='button' - no need to use curly braces

2021-02-18 17:19 UTC, MadaShindeInai commented on src/modules/TeamsList/index.tsx
> +  const myTeam = teams.results.find(
Remember that it should be fixed

2021-02-18 17:21 UTC, besovadevka commented on src/appConstants/colors.ts
> +export const TABLE_POPUP_BORDER_COLOR = '#363D4833';
Это прозрачность

2021-02-18 19:40 UTC, MadaShindeInai requested changes

2021-02-18 19:40 UTC, MadaShindeInai commented on src/components/ModalCreated/index.tsx
> +      {...{ title, text, open, onClose, cancelText }}
`{...{ title, text, **text2,** open, onClose, cancelText }} `  add text2 pliz

2021-02-18 19:40 UTC, MadaShindeInai commented on src/components/ModalCreated/index.tsx
> +      {...{ title, text, open, onClose, cancelText }}
**{...{ title, text, **text2,** open, onClose, cancelText }}**   add text2 pliz

2021-02-18 19:44 UTC, MadaShindeInai approved these changes

2021-02-18 19:44 UTC, merged